### ISSUE TITLE
Needs a legend

### ISSUE THREAD

**Issue by Ytrog** [ostreifel/typescript-uml#2]
I'm using the plugin for the first time today and I'm confused about what the different colors and symbols are. What does it mean for something to be a lightblue vs a darkblue or a purple circle? What do the orange and red diamonds mean?

I would already be happy to have it explained in the README btw.

**Comment by Ytrog** [comment]
Ah, when I click on a node I see what type it is in the box in the lower right corner. So the following is correct?

- Lightblue circle: method
- Darkblue circle: constructor
- Purple circle: function
- Yellow diamond: variable
- Red diamond: alias

How are constants shown btw?

**Comment by ostreifel** [comment]
Updated v1.1.4

**Comment by Ytrog** [comment]
Cool. I'll check it out 😃
