### ISSUE TITLE
" press alt+shift+t to open a new diagram window" doesn't work for me 

### ISSUE THREAD

**Issue by zhusjfaker** [ostreifel/typescript-uml#4]
can't open  diagram window at vscode

**Comment by zhusjfaker** [comment]
![image](https://user-images.githubusercontent.com/31839470/63106770-2eb3d000-bfb6-11e9-84dc-4831f3a744c9.png)

**Comment by kumar935** [comment]
The windows shortcut for a cropped screenshot is overriding it.

Goto VS code keybind settings, search "alt shift t" and change it to something like "alt shift y" (which works for me)
